SELECT TOP (1000) [Id]
      ,[Name]
      ,[CallerName]
      ,[StateAfterWait]
	  ,[RuntimeClosureId]
      ,[Path]
      ,[ImmutableClosure]
	  ,[Discriminator]
FROM ComplexApproval_Test.[dbo].[Waits]